# Generated by Django 4.2.6 on 2023-11-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_ogrnip', models.CharField(max_length=255, verbose_name='ОГРНИП')),
                ('org_inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('org_ip', models.CharField(max_length=255, verbose_name='ИП')),
                ('con_vk', models.CharField(max_length=255, verbose_name='ВКонтакте')),
                ('con_instagram', models.CharField(max_length=255, verbose_name='Instagram')),
                ('con_whatsapp', models.CharField(max_length=255, verbose_name='WhatsApp')),
                ('con_telegram', models.CharField(max_length=255, verbose_name='Telegram')),
                ('con_phone', models.CharField(help_text='+70000000000', max_length=255, verbose_name='Телефон')),
                ('con_email', models.CharField(help_text='STUDIAARTHOLST@gmail.com', max_length=255, verbose_name='E-Mail')),
                ('site_price', models.BooleanField(default=False, help_text='Калькулятор рассчёта цены при заказе', verbose_name='Калькулятор на сайте')),
                ('site_telegram', models.TextField(help_text='Для отправки уведомлений сотрудникам', verbose_name='Токен Telegram бота')),
            ],
        ),
    ]
