# Generated by Django 4.2.6 on 2023-11-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WWW', '0002_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='con_instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='con_phone',
            field=models.CharField(blank=True, help_text='+70000000000', max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='con_telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='con_vk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='con_whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='WhatsApp'),
        ),
    ]
