# Generated by Django 4.2.6 on 2023-11-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('1', 'Заявка ожидает обработки'), ('2', 'Заявка в процессе'), ('3', 'Заявка обработана')], max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка на обратную связь',
                'verbose_name_plural': 'Заявки на обратную связь',
            },
        ),
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя сотрудника')),
                ('telegram', models.CharField(help_text='Пример: 0123456789', max_length=255, verbose_name='Telegram ID сотрудника')),
            ],
            options={
                'verbose_name': 'Пользователь телеграм',
                'verbose_name_plural': 'Пользователи телеграм',
            },
        ),
    ]
