# Generated by Django 4.2.6 on 2023-11-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0002_alter_callback_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
    ]
