# Generated by Django 4.2.6 on 2023-11-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0003_alter_callback_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='status',
            field=models.CharField(choices=[('0', 'Заявка ожидает обработки'), ('1', 'Заявка в процессе'), ('2', 'Заявка обработана')], max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='telegram',
            field=models.CharField(help_text='Получить Telegram ID можно в чате с этим ботом: <a target="_blank" href="https://t.me/getmyid_bot">https://t.me/getmyid_bot</a>', max_length=255, verbose_name='Telegram ID сотрудника'),
        ),
    ]
