# Generated by Django 4.2.6 on 2023-11-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0004_alter_callback_status_alter_telegramusers_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='status',
            field=models.CharField(choices=[('0', 'Заявка ожидает обработки'), ('1', 'Заявка в процессе'), ('2', 'Заявка обработана')], default=0, max_length=255, verbose_name='Статус'),
        ),
    ]
