# Generated by Django 4.2.6 on 2023-10-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Это статус')),
            ],
            options={
                'verbose_name': 'обработанные заказы',
                'verbose_name_plural': 'обработанные',
            },
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='ActiveOrder',
        ),
        migrations.AlterModelOptions(
            name='activeorder',
            options={'verbose_name': 'активные заказы', 'verbose_name_plural': 'активный'},
        ),
    ]
