# Generated by Django 4.2.6 on 2023-10-31 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_statusorder_alter_order_options_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: 60x60', max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'продукция',
                'verbose_name_plural': 'продукция',
            },
        ),
        migrations.AlterModelOptions(
            name='statusorder',
            options={'verbose_name': 'статус заказа', 'verbose_name_plural': 'Статусы заказов'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.statusorder', verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='CategoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: размер', max_length=120, verbose_name='Название')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.productionorder', verbose_name='Название')),
            ],
        ),
    ]
