# Generated by Django 4.2.6 on 2023-10-31 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productionorder_alter_statusorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryorder',
            name='production',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.categoryorder'),
            preserve_default=False,
        ),
    ]
