# Generated by Django 4.2.6 on 2023-10-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_categoryorder_production_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='price',
            field=models.IntegerField(default=1, help_text='Например: 1000', max_length=10, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
