# Generated by Django 4.2.6 on 2023-10-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_productionorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='upload',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
