# Generated by Django 4.2.6 on 2023-10-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_productionorder_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='price',
            field=models.IntegerField(help_text='Например: 1000', verbose_name='Цена'),
        ),
    ]
