# Generated by Django 4.2.6 on 2023-11-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_productionorder_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryorder',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='productionorder',
            options={'verbose_name': 'продукцию', 'verbose_name_plural': 'продукция'},
        ),
        migrations.AddField(
            model_name='order',
            name='production',
            field=models.ManyToManyField(to='orders.productionorder'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='upload',
            field=models.ImageField(upload_to='uploads/', verbose_name='загрузить изображение'),
        ),
    ]
