# Generated by Django 4.2.6 on 2023-11-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='загрузить изображение'),
        ),
    ]
