# Generated by Django 4.2.6 on 2023-11-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_productionorder_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='upload',
            field=models.ImageField(blank=True, default=1, upload_to='uploads/', verbose_name='загрузить изображение'),
            preserve_default=False,
        ),
    ]
