# Generated by Django 4.2.6 on 2023-11-01 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_productionorder_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.productionorder'),
            preserve_default=False,
        ),
    ]
