# Generated by Django 4.2.6 on 2023-11-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_product_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Ожидает'), ('1', 'В процессе'), ('2', 'Готов')], max_length=255, verbose_name='Статус заказа'),
        ),
        migrations.DeleteModel(
            name='StatusOrder',
        ),
    ]
