# Generated by Django 4.2.6 on 2023-11-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_productionorder_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Имя клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='client_phone',
            field=models.CharField(help_text='Необязательное поле', max_length=255, null=True, verbose_name='Телефон клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(help_text='Необязательное поле', null=True, verbose_name='Примечания для сотрудников'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Ожидает'), ('1', 'В процессе'), ('2', 'Готов')], default=1, max_length=255, verbose_name='Статус заказа'),
        ),
    ]
