# Generated by Django 4.2.6 on 2023-11-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_client_name_order_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Ожидает'), ('1', 'В процессе'), ('2', 'Готов')], default=0, max_length=255, verbose_name='Статус заказа'),
        ),
    ]
