# Generated by Django 4.2.6 on 2023-11-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_phone',
            field=models.CharField(blank=True, default=1, help_text='Необязательное поле', max_length=255, verbose_name='Телефон клиента'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, default=1, help_text='Необязательное поле', verbose_name='Примечания для сотрудников'),
            preserve_default=False,
        ),
    ]
