# Generated by Django 4.2.6 on 2023-11-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_client_phone_alter_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='price',
            field=models.IntegerField(default=0, help_text='Например: 1000', verbose_name='Цена'),
        ),
    ]
