# Generated by Django 4.2.6 on 2023-11-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_productionorder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='price',
            field=models.IntegerField(blank=True, default=1, help_text='Например: 1000', verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
