# Generated by Django 4.2.6 on 2023-11-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_productionorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryorder',
            name='coefficient',
            field=models.IntegerField(default=1, help_text='Например: один m2 равен 10', max_length=10, verbose_name='Коэфициент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Ожидает обработки'), ('1', 'В обработке'), ('2', 'В работе'), ('3', 'Готов')], default=0, max_length=255, verbose_name='Статус заказа'),
        ),
    ]
