# Generated by Django 4.2.6 on 2023-11-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'работу', 'verbose_name_plural': 'работы'},
        ),
    ]
